ecommerce/customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('login/',views.login_view,name='login'),
    path('basket/',views.basket,name='basket'),
    path('basket/',views.basket,name='basket'),
    path('add-basket/<int:product_pk>/',views.add_basket,name="add-basket"),
    path('increase-basket-item/<int:basket_pk>/',views.increase_basket_item,name="increase-basket-item"),
    path('decrease-basket-item/<int:basket_pk>/',views.decrease_basket_item,name="decrease-basket-item"),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('wish-product/<int:pk>/',views.wish_product,name='wish-product'),
    path('unwish-product/<int:pk>/',views.unwish_product,name='unwish-product'),
    path('remove-basket/<int:basket_pk>/',views.remove_basket,name="remove-basket"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n"))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('',include('shop.urls')),
    path('customer/',include('customer.urls')),
    path('payment/',include('payment.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

ecommerce/shop/urls.py
from django.urls import path,include
from . import views

app_name='shop'
urlpatterns = [
      path('i18n/', include('django.conf.urls.i18n')),
    path('',views.home,name='home'),
    path('products',views.product_list,name='product-list'),
    path('products/<int:pk>/',views.product_detail,name='product-detail'),
]

ecommerce/customer/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class WishItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,related_name='wishlist')
    created=models.DateField(auto_now_add=True)



class BasketItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,related_name='basketlist')
    count=models.IntegerField(default=0)
    size =models.ForeignKey('shop.Size',on_delete=models.CASCADE)
    color=models.ForeignKey('shop.Color',on_delete=models.CASCADE)
    created=models.DateField(auto_now_add=True)
    







class Contact(models.Model):
    name=models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.created}"
    

class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.get_full_name()
    

class Review(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='reviews')
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='reviews')
    comment=models.TextField()
    star_count=models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    created=models.DateField(auto_now_add=True)

ecommerce/customer/forms.py
from django import forms

from .models import Contact,Customer
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model=Contact
        widgets={
            'name': forms.TextInput(attrs={'class': 'form-control mb-4','placeholder':'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control mb-4','placeholder':'Your Email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control mb-4','placeholder':'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control mb-4','placeholder':'Message','rows':'8'}),
        }

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', }))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', }))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', }))
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control', }))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'class': 'form-control', }))
    password2 = forms.CharField(max_length=50, label='Password Again', widget=forms.PasswordInput(attrs={'class': 'form-control', }))
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        
        if password and password2 and password != password2:
            raise forms.ValidationError('Sifreler eyni deyil!')
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError('Bu email movcuddur!')
        return email
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and User.objects.filter(username=username).exists():
            raise forms.ValidationError('Bu username movcuddur!')
        return username
    

    def save(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        new_user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )
        customer = Customer.objects.create(user=new_user)
        return customer

ecommerce/customer/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import ContactForm,RegisterForm
from django.contrib.auth import login,authenticate,logout
from .models import WishItem,BasketItem
from django.contrib.auth.decorators import login_required
from shop.models import Product
from django.db.models import Sum,F

# Create your views here.


def contact(request):
    form=ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact.html', {'form': form, 'result': 'success'})
        return render(request, 'contact.html', {'form': form, 'result': 'fail'})
    return render(request, 'contact.html', {'form': form})


def login_view(request):
    return render(request,'login.html')


def register(request):
    form=RegisterForm()
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            customer=form.save()
            login(request, customer.user)  
            return redirect('customer:login')
    return render(request,'register.html',{'form':form})


def login_view(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request,user)
            return redirect('shop:home')
        return render(request,'login.html',{'fail':True})
    return render(request,'login.html',{})


def logout_view(request):
    logout(request)
    return redirect('customer:login')

def wishlist_view(request):
    wishlist=request.user.customer.wishlist.all()
    total_price=wishlist.aggregate(total_price=Sum('product__price'))['total_price']
    return render(request,'wishlist.html',{
        'wishlist':wishlist,
        'total_price':total_price
    })



@login_required
def wish_product(request,pk):
    product=get_object_or_404(Product,pk=pk)
    customer=request.user.customer
    WishItem.objects.create(product=product,customer=customer)
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def unwish_product(request,pk):
    product=get_object_or_404(Product,pk=pk)
    customer=request.user.customer
    WishItem.objects.filter(product=product,customer=customer).delete()
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def basket(request):
    basketlist=request.user.customer.basketlist.all().annotate(total_price=F('count')*F('product__price'))
    return render(request,'basket.html',{
        'basketlist':basketlist
    })



def add_basket(request,product_pk):
    if request.method == 'POST':
        size_pk=request.POST.get('size')
        color_pk=request.POST.get('color')
        count=request.POST.get('count')
        customer=request.user.customer
        basket=BasketItem.objects.create(product_id=product_pk, size_id=size_pk, color_id=color_pk,count=count,customer=customer)
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect('shop:home')
    

def increase_basket_item(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    basket.count=F('count')+1
    basket.save()
    return redirect('customer:basket')

def decrease_basket_item(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    if basket.count==1:
        basket.delete()
    else:
        basket.count=F('count')-1
        basket.save()
    return redirect('customer:basket')


@login_required
def remove_basket(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    basket.delete()
    return redirect('customer:basket')

ecommerce/customer/templates/basket.html
{% extends "layout.html" %}

{% block title %}Cart sehifesi{% endblock title %}








{% block main %}
  <!-- Breadcrumb Start -->
  <div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                  
                  {% for basket in basketlist  %}
                  
                  <tr>
                    <td class="align-middle"><img src="{{basket.product.images.first.image.url}}" alt="" style="width: 50px;"> {{basket.product.title}}</td>

                      <td class="align-middle">AZN {{basket.product.price}}</td>
                      <td class="align-middle">
                        <div class="input-group quantity mx-auto" style="width: 100px;">
                              <div class="input-group-btn">
                                    <a type="button" href="{% url 'customer:decrease-basket-item' basket_pk=basket.pk %}" class="btn btn-sm btn-primary btn-minus">

                                  <i class="fa fa-minus"></i>
                                    </a>
                              </div>
                              <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{basket.count}}" name="count">
                              <div class="input-group-btn">
                                <a type="button" href="{% url 'customer:increase-basket-item' basket_pk=basket.pk %}" class="btn btn-sm btn-primary btn-minus">

                                    <i class="fa fa-plus"></i>
                                      </a>
                              </div>
                          </div> 
         
                      </td>
                      <td class="align-middle">AZN{{basket.total_price}}</td>
                      <td class="align-middle"><a href="{% url 'customer:remove-basket' basket_pk=basket.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                  </tr>
                  
                  {% endfor %}
       
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>$150</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>$160</h5>
                    </div>
                    <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->


{% endblock main %}
  

ecommerce/customer/templates/contact.html
{% extends "layout.html" %}
{% load static %}


{% block main %}



    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <span class="breadcrumb-item active">Contact</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    {% if result == 'success' %}
                    <div class="alert alert-success" role="alert">
                        Ugurla gonderildi
                      </div>
                    
                      {% elif  result == 'fail' %}
                      <div class="alert alert-danger" role="alert">
                          Muracietiniz gonderilmedi !!
                        </div>

                    {% endif %}
                    
                    <form method='POST'>
                        {% csrf_token %}
                        <div class="control-group">
                            {{form.name}}
                            {% for error in form.name.error  %}
                            <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group">
                            {{form.email}}
                            {% for error in form.email.error  %}
                            <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group">
                            {{form.subject}}
                            {% for error in form.subject.error  %}
                            <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group">
                            {{form.message}}
                            {% for error in form.message.error  %}
                            <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <div class="bg-light p-30 mb-30">
                    <iframe style="width: 100%; height: 250px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                    frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
                <div class="bg-light p-30 mb-3">
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->



{% endblock main %}

ecommerce/customer/templates/login.html
{% extends 'layout.html' %}

{% block main %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 bg-primary p-4 rounded shadow">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col h3 text-center">Login</div>
                        </div>
                    </div>
                    <div class="col-12">
                 
                        <form method="POST">
                            {% csrf_token %}
                            {% if fail %}
                                <div class="text-danger">Username yada password sehvdir</div>
                            
                            {% endif %}
                            <div class="form-group">
                              <label for="username">Username</label>
                              <input id="username" type="text" class="form-control" name="username" >
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Password</label>
                              <input type="password" class="form-control"  name="password">
                            </div>
                            <div class="form-group form-check">
                              <input type="checkbox" name="remember_me" class="form-check-input" id="exampleCheck1">
                              <label class="form-check-label" for="exampleCheck1">Remember Me</label>
                            </div>
                            
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-secondary">Submit</button>
                            </div>
              
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

ecommerce/customer/templates/register.html
{% extends 'layout.html' %}


{% block main %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-5 bg-primary p-4 rounded shadow">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col h3 text-center">Register</div>
                    </div>
                </div>
                <div class="col-12">
                  
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {% for field in form  %}
                                <label for="{{ form.subject.id_for_label}}">{{field.label}}</label>
                                {{field}}
                                <div class="mb-1">
                                  {% for error in field.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>

                            {% endfor %}
                            <div class="mb-1">
                              {% for error in form.non_field_errors %}
                                <small class="text-danger">{{error}}</small>
                              {% endfor %}
                            </div>

                        </div>
                    </div>
                    <div class="form-group form-check">
                      <input type="checkbox" class="form-check-input" name="accepted" id="exampleCheck1">
                      <a class="text-dark" href="#">Accept Terms and Conditions</a>
                      {% if not_accepted %}
                        <small class="text-danger">Sertler qebul edilmelidir!</small>
                      {% endif %}
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-secondary">Submit</button>
                    </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>





{% endblock main %}

ecommerce/customer/templates/wishlist.html
{% extends 'layout.html' %}
{% block title %}
{% load shop_helper %}
<title>Wishlist</title>
{% endblock title %}

{% block main %}


    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for wishitem in wishlist  %}
                        <tr>
                            <td class="align-middle"><img src="{{wishitem.product.images.first.image.url}}" alt="" style="width: 50px;"></td>
                            <td class="align-middle">{{wishitem.product.title}}</td>
                            <td class="align-middle">AZN{{wishitem.product.price}}</td>
                            
                            <td class="align-middle"><a href="{% url 'customer:unwish-product' pk=wishitem.product.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                            {% endfor %}
               
                        </tr>
            
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
              
              
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>AZN{{total_price|floatformat}}</h5>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->


{% endblock main %}