ecommerce/customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('login/',views.login_view,name='login'),
    path('basket/',views.basket,name='basket'),
    path('basket/',views.basket,name='basket'),
    path('add-basket/<int:product_pk>/',views.add_basket,name="add-basket"),
    path('increase-basket-item/<int:basket_pk>/',views.increase_basket_item,name="increase-basket-item"),
    path('decrease-basket-item/<int:basket_pk>/',views.decrease_basket_item,name="decrease-basket-item"),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('wish-product/<int:pk>/',views.wish_product,name='wish-product'),
    path('unwish-product/<int:pk>/',views.unwish_product,name='unwish-product'),
    path('remove-basket/<int:basket_pk>/',views.remove_basket,name="remove-basket"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n"))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('',include('shop.urls')),
    path('customer/',include('customer.urls')),
    path('payment/',include('payment.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

ecommerce/shop/urls.py
from django.urls import path,include
from . import views

app_name='shop'
urlpatterns = [
      path('i18n/', include('django.conf.urls.i18n')),
    path('',views.home,name='home'),
    path('products',views.product_list,name='product-list'),
    path('products/<int:pk>/',views.product_detail,name='product-detail'),
]

ecommerce/templates/includes/nav-categories.html
{% load i18n %}

<div class="navbar-nav w-100">
    {% for general_category in  general_categories %}
    <div class="nav-item dropdown dropright">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{general_category.title}} <i class="fa fa-angle-right float-right mt-1"></i></a>
        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
            {% for category in general_category.sub_categories.all %}
            <a href="" class="dropdown-item">{{category.title}}</a>
            
            {% endfor %}
        </div>
    </div>
    
    {% endfor %}

  {% for category in pure_categories  %}
  
  <a href="" class="nav-item nav-link">{{category.title}}</a>
  
  {% endfor %}
</div>

ecommerce/templates/includes/product-cart.html
{% load shop_helper %}

<div class="col-lg-4 col-md-6 col-sm-6 pb-1">
    <div class="product-item bg-light mb-4">
        <div class="product-img position-relative overflow-hidden">
            <img class="img-fluid w-100" style="height:250px;object-fit:cover" src="{{product.images.first.image.url}}" alt="">
            <div class="product-action">
                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
    {% if product|is_wished:request %}
    <a class="btn btn-outline-dark btn-square" href="{% url 'customer:unwish-product' product.pk %}"><i class="fas fa-heart"></i></a>
    {% else %}
    <a class="btn btn-outline-dark btn-square" href="{% url 'customer:wish-product' product.pk %}"><i class="far fa-heart"></i></a>


    {% endif %}                
                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
            </div>
        </div>
        <div class="text-center py-4">
            <a class="h6 text-decoration-none text-truncate" href="{% url 'shop:product-detail' pk=product.pk %}">{{product.title}}</a>
            <div class="d-flex align-items-center justify-content-center mt-2">
                {% if product.old_price %}
                <h5>{{product.price}}</h5><h6 class="text-muted ml-2"><del>AZN{{product.old_price}}</del></h6>
                
                
                {% else %}
                <h6 class="text-muted ml-2">AZN{{product.price}}</h6>
                {% endif %}
        
        </div>
            <div class="d-flex align-items-center justify-content-center mb-1">
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small>(99)</small>
            </div>
        </div>
    </div>
</div>